#!/usr/bin/env python3
# Copyright 2026 Velle Sinclair.
#
# Simplified BSD License or GPLv3, like the rest of this tree.

"""Runs Mac OS X Carbon applications under maloader-carbon."""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from maloader_carbon import launcher_app  # noqa: E402

sys.exit(launcher_app.main(sys.argv[1:]))
