#!/usr/bin/env python3
# Copyright 2026 Velle Sinclair.
#
# Simplified BSD License or GPLv3, like the rest of this tree.

"""Installs Halo: Combat Evolved's Mac release to run under maloader-carbon."""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from maloader_carbon import installer_app  # noqa: E402

sys.exit(installer_app.main(sys.argv[1:]))
